services:
  - type: web
    name: fitness-app-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: npm install && python3 -m pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
