import { Pool } from 'pg';
import dotenv from 'dotenv';

dotenv.config();

const pool = new Pool({
  connectionString: process.env.POSTGRES_URL,
});

async function clearTasksAndTest() {
  try {
    console.log('🧹 Starting task cleanup and auto-generation test...\n');

    // 1. Delete all tasks
    console.log('1️⃣ Deleting all tasks...');
    const deleteResult = await pool.query('DELETE FROM tasks');
    console.log(`   ✅ Deleted ${deleteResult.rowCount} tasks\n`);

    // 2. Check task count
    console.log('2️⃣ Verifying task count...');
    const countResult = await pool.query('SELECT COUNT(*) FROM tasks');
    const taskCount = countResult.rows[0].count;
    console.log(`   ✅ Tasks remaining: ${taskCount}\n`);

    // 3. Get a test user
    console.log('3️⃣ Finding a test user...');
    const userResult = await pool.query(`
      SELECT u.id, u.email
      FROM users u
      LIMIT 1
    `);

    if (userResult.rows.length === 0) {
      console.log('   ⚠️ No test user found. Please create a user first.');
      await pool.end();
      return;
    }

    const testUser = userResult.rows[0];
    console.log(`   ✅ Test user found: ${testUser.email}`);
    console.log(`   � User ID: ${testUser.id}\n`);

    // 4. Check if user has any tasks now
    console.log('4️⃣ Checking user tasks after cleanup...');
    const userTasksResult = await pool.query(`
      SELECT id, title
      FROM tasks 
      WHERE user_id = $1
      ORDER BY created_at DESC
    `, [testUser.id]);
    
    console.log(`   📋 User tasks: ${userTasksResult.rows.length}`);
    if (userTasksResult.rows.length === 0) {
      console.log('   ✅ User has NO tasks (ready for auto-generation test)\n');
    } else {
      console.log('   ⚠️ User still has tasks:');
      userTasksResult.rows.forEach(task => {
        console.log(`      - ${task.title} (${task.id})`);
      });
      console.log();
    }

    // 5. Show next steps
    console.log('✅ CLEANUP COMPLETE\n');
    console.log('📝 NEXT STEPS:\n');
    console.log('1. The task list is now EMPTY');
    console.log('2. When you call GET /api/tasks/today, auto-generation should trigger');
    console.log('3. You should see new tasks generated automatically\n');
    
    console.log('🔗 API ENDPOINT TO TEST:');
    console.log(`   GET http://localhost:5000/api/tasks/today`);
    console.log(`   Authorization: Bearer {your-token}\n`);

    console.log('💡 EXPECTED BEHAVIOR:');
    console.log('   - Response: autoGenerated: true');
    console.log('   - Response includes 4 new tasks');
    console.log('   - Each task has stat_rewards');
    console.log('   - stat_recommendations included\n');

    await pool.end();

  } catch (err) {
    console.error('❌ Error:', err.message);
    await pool.end();
    process.exit(1);
  }
}

clearTasksAndTest();
